-   id: python-version-check-runtime-txt
    name: python-version-check-runtime-txt
    description: Ensure the Python version in runtime.txt matches Pipfile.lock
    entry: check_runtime_txt
    language: python
    types: [file]
