-   id: python-version-check-runtime-txt
    name: python-version-check-runtime-txt
    description: Ensure the Python version in runtime.txt matches Pipfile.lock
    entry: heck_runtime_txt.py
    language: python
    types: [file]
